# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-02 20:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='defaultStatus',
            new_name='default_status',
        ),
    ]
