# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-02 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20160802_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='default_status',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
